### ISSUE TITLE
Linking DCMQI to a dynamic library fails on linux

### ISSUE THREAD

**Issue by nolden** [QIICR/dcmqi#301] opened 2017-09-01 13:01 UTC
If you link the static dcmqi libraries to another dynamic library like a plugin, you get linker errors, like this one: http://cdash.mitk.org/viewBuildError.php?buildid=652980

A proper solution would be a dynamic dcmqi library but that requires symbol export (declspec stuff on Windows ...). For now, I would solve this by adding -fPIC to linux builds which allows for relinking.

**Comment by fedorov** [comment] 2017-09-01 13:46
xref #303

**Comment by fedorov** [comment] 2017-09-07 19:54
Closing this, since #303 was merged - @nolden please reopen if the issue is not resolved!

**Closed by fedorov** 2017-09-07 19:54 UTC
Labels: bug
